{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "85dc3c6a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sqlalchemy import create_engine\n",
    "\n",
    "# ----------------------------\n",
    "# Step 1: Load Cleaned Data\n",
    "# ----------------------------\n",
    "health_df = pd.read_csv('data/health_data_cleaned.csv')\n",
    "finance_df = pd.read_csv('data/finance_data_cleaned.csv')\n",
    "\n",
    "# ----------------------------\n",
    "# Step 2: Connect to SQL (Optional)\n",
    "# ----------------------------\n",
    "engine = create_engine('sqlite:///data/analytics.db')\n",
    "\n",
    "# Query example\n",
    "health_sql = pd.read_sql('SELECT * FROM health_data', engine)\n",
    "finance_sql = pd.read_sql('SELECT * FROM finance_data', engine)\n",
    "\n",
    "# ----------------------------\n",
    "# Step 3: Health Data Analysis\n",
    "# ----------------------------\n",
    "# Summary statistics\n",
    "print(health_df.describe())\n",
    "\n",
    "# Daily Steps Trend\n",
    "plt.figure(figsize=(10,5))\n",
    "sns.lineplot(x='Date', y='Steps', data=health_df)\n",
    "plt.title(\"Daily Steps Trend\")\n",
    "plt.xticks(rotation=45)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Sleep Hours Distribution\n",
    "plt.figure(figsize=(8,5))\n",
    "sns.histplot(health_df['SleepHours'], bins=10, kde=True)\n",
    "plt.title(\"Sleep Hours Distribution\")\n",
    "plt.show()\n",
    "\n",
    "# Average Heart Rate by Day\n",
    "avg_hr = health_df.groupby('Day')['HeartRate'].mean().reindex(\n",
    "    ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])\n",
    "avg_hr.plot(kind='bar', figsize=(8,5), title=\"Average Heart Rate by Day\")\n",
    "plt.show()\n",
    "\n",
    "# ----------------------------\n",
    "# Step 4: Finance Data Analysis\n",
    "# ----------------------------\n",
    "# Total Income vs Expenses\n",
    "finance_summary = finance_df.groupby('Category')['Amount'].sum().reset_index()\n",
    "sns.barplot(x='Category', y='Amount', data=finance_summary)\n",
    "plt.title(\"Total Income vs Expenses\")\n",
    "plt.show()\n",
    "\n",
    "# Monthly Expenses Trend\n",
    "monthly_expense = finance_df[finance_df['Category']=='Expense'].groupby('Month')['Amount'].sum()\n",
    "monthly_expense.plot(kind='line', marker='o', title=\"Monthly Expenses Trend\")\n",
    "plt.show()\n",
    "\n",
    "# Top Expense Categories\n",
    "top_expense = finance_df[finance_df['Category']=='Expense'].groupby('Notes')['Amount'].sum().sort_values(ascending=False)\n",
    "top_expense.plot(kind='bar', figsize=(8,5), title=\"Top Expense Categories\")\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
